/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_qabel_core_crypto_Curve25519 */

#ifndef _Included_de_qabel_core_crypto_Curve25519
#define _Included_de_qabel_core_crypto_Curve25519
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_qabel_core_crypto_Curve25519
 * Method:    cryptoScalarmult
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_qabel_core_crypto_Curve25519_cryptoScalarmult
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     de_qabel_core_crypto_Curve25519
 * Method:    cryptoScalarmultBase
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_qabel_core_crypto_Curve25519_cryptoScalarmultBase
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
